---
title: "Covid Vignette"
author: "Xavier Genelin"
date: "9/29/2021"
output: 
  github_document:
    toc: True
    html_preview: False
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

-`tidyverse`  
-`httr`  
-`jsonlite`  

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(httr)
library(jsonlite)
```

## Functions

This will be used in each of the functions to get the data from the API. Just an example for easy copying
```{r}
getAPI <- GET("https://api.covid19api.com/all")

dat <- fromJSON(rawToChar(getAPI$content))

as_tibble(dat)
```


```{r}
# The user can either choose a global summary or country

covidSummary <- function(type = "global"){
  ### you can either select global or country to see the global summary or 
  # the summary by country
  getAPI <- GET("https://api.covid19api.com/summary")
  dat <- fromJSON(rawToChar(getAPI$content))
  
  if(type == "global"){
    output <- as_tibble(dat$Global)
  } else if(type == "country"){
    output <- as_tibble(dat$Countries)
    
    output <- output %>% select("Country", "CountryCode", "Slug", "NewConfirmed", 
                                "TotalConfirmed", "NewDeaths", "TotalDeaths", "NewRecovered", "TotalRecovered", "Date")
  }
  return(output)
}
```

```{r}
a <- covidSummary("country")
a
```

```{r}
getAPI <- GET("https://api.covid19api.com/countries")

dat <- fromJSON(rawToChar(getAPI$content))

as_tibble(dat)
```

Need this because country filters need to be the slug, so the user can choose anything but return the slug
```{r}
getCountry <- function(country, IDType){
  # This will return a tibble with the country name, the country name in lowercase
  # with dashes instead of spaces (slug), and the country code of length 2
  # For example, if we want the United States:
  # country: United States of America, slug: united-states, id: US
  getAPI <- GET("https://api.covid19api.com/countries")
  dat <- fromJSON(rawToChar(getAPI$content))
  data <- as_tibble(dat)
  
  if(IDType == "country"){
    output <- data %>% filter(Country == country) %>% select(Slug)
  } else if(IDType == "id"){
    output <- data %>% filter(ISO2 == toupper(country)) %>% select(Slug)
  } else if(IDType == "slug"){
    output <- data %>% filter(slug == country) %>% select(Slug)
  } else {
    stop("ERROR: Invalid IDType. Should be country, id, or slug")
  }
  
  if(nrow(output) == 0){
    stop("ERROR: Country not found. Check spelling and possible capitalization")
  }
  return(output)
}

```

```{r}
getAPI <- GET("https://api.covid19api.com/total/country/united-states/status/death")
dat <- fromJSON(rawToChar(getAPI$content))
data <- as_tibble(dat)

data[1,1] == ""
```

```{r}
countryTotal <- function(country, IDType, case = "all") {
  # get the total covid numbers for a country by day
  # user has the option to get all numbers or just confirmed, recovered, or deaths
  if(case == "all"){
    main <- "https://api.covid19api.com/total/country/"
    country <- getCountry(country, IDType)
    url <- paste0(main, country)
    getAPI <- GET(url)
    dat <- fromJSON(rawToChar(getAPI$content))
    output <- as_tibble(dat)
    
  } else if(case != "all"){
    main <- "https://api.covid19api.com/total/country/"
    country <- getCountry(country, IDType)
    url <- paste0(main, country, "/status/", case)
    getAPI <- GET(url)
    dat <- fromJSON(rawToChar(getAPI$content))
    output <- as_tibble(dat)
  } 
  if(output[1,1] == ""){
    stop("ERROR: make sure case is either all, confirmed, recovered, or deaths")
  }
  return(output)
}

countryTotal(country= "AL", IDType = "id", case = "recovered")
```

```{r}
getAPI <- GET("https://api.covid19api.com/all")
dat <- fromJSON(rawToChar(getAPI$content))
dat
```


## Data Exporation

```{r}
data1 <- covidSummary(type = "country")

ggplot(data1, aes(x = NewConfirmed, y = NewDeaths)) +
  geom_point()
```


